=pod

=head1 NAME

dmenu_launch - launch XDG applications using dmenu

=head1 SYNOPSIS

dmenu_launch [dmenu options]

=head1 DESCRIPTION

B<dmenu_launch> is a script that can be used by L<dwm(1)> (or other
tiling window manager that use L<dmenu(1)>) which lists desktop
applications in XDG directories as input to L<dmenu(1)> and runs the
result using L<xdg-launch(1)>.

=head1 OPTIONS

Takes the same options as L<dmenu(1)>.

=head1 BUGS

B<dmenu_launch> has no known bugs.
Please report bugs to the source code repository at
L<https://github.com/bbidulock/xdg-launch/issues>.

=head1 SEE ALSO

L<dmenu(1)>,
L<stest(1)>,
L<xdg-launch(1)>

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
