=pod

=head1 NAME

xdg-prefs - locate and set preferred desktop applications

=head1 SYNOPSIS

B<xdg-prefs> [I<options>] {-p,--pref} [--] I<APPID> [I<TYPE> [...]]

B<xdg-prefs> [I<options>] {-e,--exec} [--] I<TYPE>

B<xdg-prefs> [I<options>] {-l,--list} [--] I<TYPE> [...]

=head1 DESCRIPTION

B<xdg-prefs> operates in two modes: (1) locates preferred applications
by category or mime type; and (2) sets preferred applications by
category or mime type.

=head1 ARGUMENTS

The program accepts the following arguments:

=over

=item I<APPID>

Specifies the application identifier of an XDG desktop application to
locate.  The application identifier, I<APPID>, can be one of the
following:

=over

=item 1.

the name of a desktop entry file without the F<.desktop> suffix (e.g.
C<gvim>); the name may contain a C</> if it is specified relative to a
user or system application directory, in which case it must not start
with a C</> or C<.>.

=item 2.

the name of a desktop entry file with the F<.desktop> suffix (e.g.
C<gvim.desktop>); the same restrictions as (1), above, apply; or,

=item 3.

the full path (absolute or relative) and filename of a desktop entry
file (e.g.  C</usr/share/applications/gvim.desktop>); the full path must
contain at least one C</> and start with either a C</> or a C<.>.

=back

Providing a non-option application identifier argument is mandatory when
the B<--pref> option is specified.

=item I<TYPE>

Specifies the type of application for which to show or set I<APPID>
as the preferred application.  The application type, I<TYPE>, can be one
of the following:

=over

=item 1.

A recognized XDG category name (e.g. C<TextEditor>).  For recognized XDG
category names, see L</XDG CATEGORIES>.

=item 2.

A mime (content) type (e.g. C<text/plain>).  All mime types have a C</>
in their names and are thus distinguished from XDG categories.  The
content type cannot contain wild cards (i.e. it cannot contain C<*>).

=back

=back

=head1 OPTIONS

The options that are detailed below are recognized by B<xdg-prefs>.
B<xdg-prefs> uses L<getopt_long_only(3)>, so unambiguous abbreviations
of long options and long options with a single dash are also supported.

=head2 COMMAND OPTIONS

One of the following command options must be specified to set the
command mode:

=over

=item B<-p>, B<--pref> [--] I<APPID>[;...] [I<TYPE> [...]]

Specifies that I<APPID> is to be used as the default or preferred
application for I<TYPE>.  When additional application identifiers,
I<APPID>, are specified, separated by semicolons (C<;>), the application
identifiers specify the order of preference of applications for the mime
types or categories, I<TYPE>.

When no mime types nor categories are specified, the mime types and
categories for which to set the application identifier will be taken
from the application's F<.desktop> file.

When multiple mime types or categories are specified, the applications
will be set against each mime type and category specified.

=item B<-e>, B<--exec> [--] I<TYPE>

Execute the preferred application corresponding to the specified mime
type or category, I<TYPE>.  It is an error when no usable application
has been assigned to the specified I<TYPE>.

=item B<-l>, B<--list> [--] I<TYPE> [...]

List the preferred applications (by application identifier)
corresponding to the specified mime types or categories, I<TYPE>.

=item B<-h>, B<--help>, B<-H>, B<-?>, B<--?>

Prints usage information to standard output and exits.

=item B<-V>, B<--version>

Prints detailed version information and exits.

=item B<-C>, B<--copying>

Prints detailed copying permissions and exits.

=back

=head2 GENERAL OPTIONS

The following general options are recognized:

=over

=item B<-r>, B<--recommend>

When listing, launching or setting preferred applications, use the
recommended application instead of the default application for the given
type.

=item B<-f>, B<--fallback>

When listing or launching preferred applications, use the fallback
application instead of the default or recommended application for the
given type.

=item B<-t>, B<--textonly>

When listing, launching or setting preferred applications, only list,
launch or set applications that run in a terminal.  Note that this is
the default behaviour when the B<DISPLAY> environment variable is not
set.

=item B<--P>, B<--pointer>

Passes the B<--pointer> option to L<xdg-launch(1)> when launching the
application.

=item B<--K>, B<--keyboard>

Passes the B<--keyboard> option to L<xdg-launch(1)> when launching the
application.

=back


=head1 XDG CATEGORIES

In the category listings below, the more specific category is listed
first and then the more general categories are listed following a
semicolon.

The following XDG categories are recognized and tracked by the program:

=over

=item C<Building;Development>

A tool to build applications.  One mime type is
F<application/x-cmakecache>, but it is application specific, so
B<xdg-prefs> only tracks these applications by category.

=item C<Debugger;Development>

A tool to debug applications.  No known mime type.  These applications
are only tracked by category.

=item C<IDE;Development>

Integrated Development Environment (IDE) application.  Some mime types
are F<text/x-chdr>, F<text/x-csrc>, F<text/x-c++hdr>, F<text/x-c++src>,
F<text/x-java>, F<text/x-dsrc>, F<text/x-pascal>, F<text/x-perl>,
F<text/x-python>.  These applications have a wide range of mime types,
so they are only tracked by category.

=item C<GUIDesigner;Development>

A GUI designer application.  Some mime types are
F<application/x-designer>, F<application/x-fluid>; however, these mime
types are application specific so they are only tracked by category.

=item C<Profiling;Development>

A profiling tool.  No commonly known tools or mime types.  These
applications are only tracked by category.

=item C<RevisionControl;Development>

Applications like cvs or subversion.  No commonly known mime types.
Some examples are F<bzr-explorer.desktop> and there should be a
F<gitk.desktop>.  These applications are only tracked by category.

=item C<Translation;Development>

A translation tool.  Only tool I know of is F<linguist.desktop> with
mime types F<text/vnd.trolltech.linguist> and F<application/x-linguist>;
however, these mime types are application specific, so they are only
tracked by category.

=item C<Calendar;Office>

Calendar application.
Only application I know that is marked like this is F<etm.desktop> with
no mime types.

=item C<ContactManager;Office>

Address books, contact lists, LDIF file manipulation.
No commonly known applications or mime types.  But surely an LDIF file would do.

=item C<Database;Office>

=item C<Database;Development>

=item C<Database;AudioVideo>

Application to manage a database.
Applications are F<base.desktop> with mime types
F<application/vnd.oasis.opendocument.database> and
F<application/vnd.sun.xml.base>;
and F<gmdb.desktop>, with mime types
F<application/vnd.ms-access>,
F<application/x-msaccess>,
F<application/msaccess>,
F<application/vnd.msaccess>,
F<application/mdb>,
F<application/x-mdb>.

=item C<Dictionary;Office>

=item C<Dictionary;TextTools>

A dictionary.
No commonly known applications or mime types.

=item C<Chart;Office>

Chart application.
No commonly known applications or mime types.

=item C<Email;Office>

=item C<Email;Network>

Email application.  Many applications with mime types
F<x-scheme-handler/mailto> and
F<message/rfc822>.

=item C<FlowChart;Office>

A flowchart application.
Applications F<dia.desktop> with mime types
F<application/x-dia-diagram>; and
F<libreoffice-draw.desktop> with mime types
F<application/vnd.oasis.opendocument.graphics>,
F<application/vnd.oasis.opendocument.graphics-flat-xml>,
F<application/vnd.oasis.opendocument.graphics-template>,
F<application/vnd.sun.xml.draw>,
F<application/vnd.sun.xml.draw.template>,
F<application/vnd.visio>,
F<application/x-wpg>,
F<application/vnd.corel-draw>,
F<application/vnd.ms-publisher>,
F<image/x-freehand>,
F<application/clarisworks>.

=item C<PDA;Office>

Tool to manage your PDA.
No commonly known applications or mime types.

=item C<ProjectManagement;Office>

=item C<ProjectManagement;Development>

Project management application.
No commonly known applications or mime types.

=item C<Presentation;Office>

Presentation software.
F<libreoffice-impress.desktop> with mime types
F<application/vnd.oasis.opendocument.presentation>,
F<application/vnd.oasis.opendocument.presentation-template>,
F<application/vnd.sun.xml.impress>,
F<application/vnd.sun.xml.impress.template>,
F<application/mspowerpoint>,
F<application/vnd.ms-powerpoint>,
F<application/vnd.openxmlformats-officedocument.presentationml.presentation>,
F<application/vnd.ms-powerpoint.presentation.macroenabled.12>,
F<application/vnd.openxmlformats-officedocument.presentationml.template>,
F<application/vnd.ms-powerpoint.template.macroenabled.12>,
F<application/vnd.openxmlformats-officedocument.presentationml.slide>,
F<application/vnd.openxmlformats-officedocument.presentationml.slideshow>,
F<application/vnd.ms-powerpoint.slideshow.macroEnabled.12>,
F<application/vnd.oasis.opendocument.presentation-flat-xml>,
F<application/x-iwork-keynote-sffkey>.
Perhaps the oasis and microsoft mime types are the most common.

=item C<Spreadsheet;Office>

A spreadsheet.
F<libreoffice-calc.desktop> with mime types
F<application/vnd.oasis.opendocument.spreadsheet>,
F<application/vnd.oasis.opendocument.spreadsheet-template>,
F<application/vnd.sun.xml.calc>,
F<application/vnd.sun.xml.calc.template>,
F<application/msexcel>,
F<application/vnd.ms-excel>,
F<application/vnd.openxmlformats-officedocument.spreadsheetml.sheet>,
F<application/vnd.ms-excel.sheet.macroenabled.12>,
F<application/vnd.openxmlformats-officedocument.spreadsheetml.template>,
F<application/vnd.ms-excel.template.macroenabled.12>,
F<application/vnd.ms-excel.sheet.binary.macroenabled.12>,
F<text/csv>,
F<application/x-dbf>,
F<text/spreadsheet>,
F<application/csv>,
F<application/excel>,
F<application/tab-separated-values>,
F<application/vnd.lotus-1-2-3>,
F<application/vnd.oasis.opendocument.chart>,
F<application/vnd.oasis.opendocument.chart-template>,
F<application/x-dbase>,
F<application/x-dos_ms_excel>,
F<application/x-excel>,
F<application/x-msexcel>,
F<application/x-ms-excel>,
F<application/x-quattropro>,
F<application/x-123>,
F<text/comma-separated-values>,
F<text/tab-separated-values>,
F<text/x-comma-separated-values>,
F<text/x-csv>,
F<application/vnd.oasis.opendocument.spreadsheet-flat-xml>,
F<application/vnd.ms-works>,
F<application/clarisworks>.

=item C<WordProcessor;Office>

A word processor.
F<abiword.desktop> with mime types
F<application/x-abiword>,
F<text/x-abiword>,
F<text/x-xml-abiword>,
F<text/plain>,
F<application/msword>,
F<application/rtf>,
F<application/vnd.plain>,
F<application/xhtml+xml>,
F<text/html>,
F<application/x-crossmark>,
F<application/docbook+xml>,
F<application/x-t602>,
F<application/vnd.oasis.opendocument.text>,
F<application/vnd.oasis.opendocument.text-template>,
F<application/vnd.oasis.opendocument.text-web>,
F<application/vnd.sun.xml.writer>,
F<application/vnd.stardivision.writer>,
F<text/vnd.wap.wml>,
F<application/wordperfect6>,
F<application/wordperfect5.1>,
F<application/vnd.wordperfect>,
F<application/x-abicollab>; and
F<libreoffice-writer.desktop> with mime types
F<application/vnd.oasis.opendocument.text>,
F<application/vnd.oasis.opendocument.text-template>,
F<application/vnd.oasis.opendocument.text-web>,
F<application/vnd.oasis.opendocument.text-master>,
F<application/vnd.sun.xml.writer>,
F<application/vnd.sun.xml.writer.template>,
F<application/vnd.sun.xml.writer.global>,
F<application/msword>,
F<application/vnd.ms-word>,
F<application/x-doc>,
F<application/x-hwp>,
F<application/rtf>,
F<text/rtf>,
F<application/vnd.wordperfect>,
F<application/wordperfect>,
F<application/vnd.lotus-wordpro>,
F<application/vnd.openxmlformats-officedocument.wordprocessingml.document>,
F<application/vnd.ms-word.document.macroenabled.12>,
F<application/vnd.openxmlformats-officedocument.wordprocessingml.template>,
F<application/vnd.ms-word.template.macroenabled.12>,
F<application/vnd.ms-works>,
F<application/vnd.stardivision.writer-global>,
F<application/x-extension-txt>,
F<application/x-t602>,
F<text/plain>,
F<application/vnd.oasis.opendocument.text-flat-xml>,
F<application/x-fictionbook+xml>,
F<application/macwriteii>,
F<application/x-aportisdoc>,
F<application/prs.plucker>,
F<application/vnd.palm>,
F<application/clarisworks>.

=item C<2DGraphics;Graphics>

2D based graphical application.

=item C<VectorGraphics;2DGraphics;Graphics>

Application for viewing, creating, or processing vector graphics.
F<evince-previewer.desktop> with mime types
F<application/pdf>,
F<application/x-bzpdf>,
F<application/x-gzpdf>,
F<application/x-xzpdf>,
F<application/x-ext-pdf>,
F<application/postscript>,
F<application/x-bzpostscript>,
F<application/x-gzpostscript>,
F<image/x-eps>,
F<image/x-bzeps>,
F<image/x-gzeps>,
F<application/x-ext-ps>,
F<application/x-ext-eps>,
F<application/x-dvi>,
F<application/x-bzdvi>,
F<application/x-gzdvi>,
F<application/x-ext-dvi>,
F<image/vnd.djvu>,
F<image/vnd.djvu+multipage>,
F<application/x-ext-djv>,
F<application/x-ext-djvu>,
F<image/tiff>,
F<application/x-cbr>,
F<application/x-cbz>,
F<application/x-cb7>,
F<application/x-cbt>,
F<application/x-ext-cbr>,
F<application/x-ext-cbz>,
F<application/x-ext-cb7>,
F<application/x-ext-cbt>,
F<application/oxps>,
F<application/vnd.ms-xpsdocument>;
F<evince.desktop> with mime types
F<application/pdf>,
F<application/x-bzpdf>,
F<application/x-gzpdf>,
F<application/x-xzpdf>,
F<application/x-ext-pdf>,
F<application/postscript>,
F<application/x-bzpostscript>,
F<application/x-gzpostscript>,
F<image/x-eps>,
F<image/x-bzeps>,
F<image/x-gzeps>,
F<application/x-ext-ps>,
F<application/x-ext-eps>,
F<application/x-dvi>,
F<application/x-bzdvi>,
F<application/x-gzdvi>,
F<application/x-ext-dvi>,
F<image/vnd.djvu>,
F<image/vnd.djvu+multipage>,
F<application/x-ext-djv>,
F<application/x-ext-djvu>,
F<image/tiff>,
F<application/x-cbr>,
F<application/x-cbz>,
F<application/x-cb7>,
F<application/x-cbt>,
F<application/x-ext-cbr>,
F<application/x-ext-cbz>,
F<application/x-ext-cb7>,
F<application/x-ext-cbt>,
F<application/oxps>,
F<application/vnd.ms-xpsdocument>;
F<inkscape.desktop> with mime types
F<image/svg+xml>,
F<image/svg+xml-compressed>,
F<application/vnd.corel-draw>,
F<application/pdf>,
F<application/postscript>,
F<image/x-eps>,
F<application/illustrator>;
F<libreoffice-draw.desktop> with mime types
F<application/vnd.oasis.opendocument.graphics>,
F<application/vnd.oasis.opendocument.graphics-flat-xml>,
F<application/vnd.oasis.opendocument.graphics-template>,
F<application/vnd.sun.xml.draw>,
F<application/vnd.sun.xml.draw.template>,
F<application/vnd.visio>,
F<application/x-wpg>,
F<application/vnd.corel-draw>,
F<application/vnd.ms-publisher>,
F<image/x-freehand>,
F<application/clarisworks>.

=item C<RasterGraphics;2DGraphics;Graphics>

Application for viewing, creating, or processing raster (bitmap)
graphics.
F<apache.en.desktop> with mime types,
F<image/bmp>,
F<image/gif>,
F<image/jpeg>,
F<image/jpg>,
F<image/png>,
F<image/tiff>,
F<image/x-bmp>,
F<image/x-pcx>,
F<image/x-tga>,
F<image/x-portable-pixmap>,
F<image/x-portable-bitmap>,
F<image/x-targa>,
F<image/x-portable-greymap>,
F<application/pcx>,
F<image/svg+xml>,
F<image/svg-xml>;
F<gtkam.desktop> with no mime types,
F<xsane.desktop> with no mime types,
F<qiv.desktop> with mime types,
F<image/bmp>,
F<image/gif>,
F<image/jpeg>,
F<image/jpg>,
F<image/pjpeg>,
F<image/png>,
F<image/tiff>,
F<image/x-bmp>,
F<image/x-gray>,
F<image/x-icb>,
F<image/x-ico>,
F<image/x-png>,
F<image/x-portable-anymap>,
F<image/x-portable-bitmap>,
F<image/x-portable-graymap>,
F<image/x-portable-pixmap>,
F<image/x-xbitmap>,
F<image/x-xpixmap>,
F<image/x-pcx>,
F<image/svg+xml>,
F<image/svg+xml-compressed>,
F<image/vnd.wap.wbmp>;
F<gpicview.desktop> with mime types,
F<image/bmp>,
F<image/gif>,
F<image/jpeg>,
F<image/jpg>,
F<image/png>,
F<image/tiff>,
F<image/x-bmp>,
F<image/x-pcx>,
F<image/x-tga>,
F<image/x-portable-pixmap>,
F<image/x-portable-bitmap>,
F<image/x-targa>,
F<image/x-portable-greymap>,
F<application/pcx>,
F<image/svg+xml>,
F<image/svg-xml>;
F<gpaint.desktop> with no mime types,
F<gthumb-import.desktop> with mime types,
F<x-content/image-dcf>,
F<x-content/image-picturecd>;
F<xzgv.desktop> with no mime types,
F<fedora-xsane.desktop> with no mime types,
F<gimp.desktop> with mime types,
F<image/bmp>,
F<image/g3fax>,
F<image/gif>,
F<image/x-fits>,
F<image/x-pcx>,
F<image/x-portable-anymap>,
F<image/x-portable-bitmap>,
F<image/x-portable-graymap>,
F<image/x-portable-pixmap>,
F<image/x-psd>,
F<image/x-sgi>,
F<image/x-tga>,
F<image/x-xbitmap>,
F<image/x-xwindowdump>,
F<image/x-xcf>,
F<image/x-compressed-xcf>,
F<image/x-gimp-gbr>,
F<image/x-gimp-pat>,
F<image/x-gimp-gih>,
F<image/tiff>,
F<image/jpeg>,
F<image/x-psp>,
F<application/postscript>,
F<image/png>,
F<image/x-icon>,
F<image/x-xpixmap>,
F<image/svg+xml>,
F<application/pdf>,
F<image/x-wmf>,
F<image/jp2>,
F<image/jpeg2000>,
F<image/jpx>,
F<image/x-xcursor>;
F<gthumb.desktop> with mime types.
F<image/bmp>,
F<image/g3fax>,
F<image/gif>,
F<image/x-fits>,
F<image/x-pcx>,
F<image/x-portable-anymap>,
F<image/x-portable-bitmap>,
F<image/x-portable-graymap>,
F<image/x-portable-pixmap>,
F<image/x-psd>,
F<image/x-sgi>,
F<image/x-tga>,
F<image/x-xbitmap>,
F<image/x-xwindowdump>,
F<image/x-xcf>,
F<image/x-compressed-xcf>,
F<image/x-gimp-gbr>,
F<image/x-gimp-pat>,
F<image/x-gimp-gih>,
F<image/tiff>,
F<image/jpeg>,
F<image/x-psp>,
F<application/postscript>,
F<image/png>,
F<image/x-icon>,
F<image/x-xpixmap>,
F<image/svg+xml>,
F<application/pdf>,
F<image/x-wmf>,
F<image/jp2>,
F<image/jpeg2000>,
F<image/jpx>,
F<image/x-xcursor>.

=item C<3DGraphics;Graphics>

Application for viewing, creating, or processing 3-D graphics.
F<blender-windowed.desktop> with mime types,
F<application/x-blender>;
F<drawxtl.desktop> with no mime types;
F<wings3d.desktop> with no mime types;
F<blender.desktop> with mime types,
F<application/blender>,
F<application/x-blender>;
F<g3dviewer.desktop> with no mime types.

=item C<Scanning;Graphics>

Tool to scan a file/text.
F<xsane.desktop> with no mime types.

=item C<OCR;Scanning;Graphics>

Optical character recognition application.
F<xsane.desktop> with no mime types.

=item C<Photography;Graphics>

=item C<Photography;Office>

Camera tools, etc.
F<apache.en.desktop> with mime types,
F<image/bmp>,
F<image/gif>,
F<image/jpeg>,
F<image/jpg>,
F<image/png>,
F<image/tiff>,
F<image/x-bmp>,
F<image/x-pcx>,
F<image/x-tga>,
F<image/x-portable-pixmap>,
F<image/x-portable-bitmap>,
F<image/x-targa>,
F<image/x-portable-greymap>,
F<application/pcx>,
F<image/svg+xml>,
F<image/svg-xml>;
F<flphoto.desktop> with mime types,
F<application/x-flphoto>;
F<gtkam.desktop> with no mime types;
F<gpicview.desktop> with mime types,
F<image/bmp>,
F<image/gif>,
F<image/jpeg>,
F<image/jpg>,
F<image/png>,
F<image/tiff>,
F<image/x-bmp>,
F<image/x-pcx>,
F<image/x-tga>,
F<image/x-portable-pixmap>,
F<image/x-portable-bitmap>,
F<image/x-targa>,
F<image/x-portable-greymap>,
F<application/pcx>,
F<image/svg+xml>,
F<image/svg-xml>;
F<gthumb.desktop> with mime types,
F<image/bmp>,
F<image/jpeg>,
F<image/gif>,
F<image/png>,
F<image/tiff>,
F<image/x-bmp>,
F<image/x-ico>,
F<image/x-png>,
F<image/x-pcx>,
F<image/x-tga>,
F<image/xpm>,
F<image/svg+xml>.

=item C<Publishing;Graphics>

=item C<Publishing;Office>

Desktop publishing applications and colour management tools.
No commonly known applications or mime types.

=item C<Viewer;Graphics>

=item C<Viewer;Office>

Tool to view e.g. a graphic or pdf file.
C<Viewer;Office> is primarily PDF viewers; C<Viewer;Graphics> are
primarily image viewers.

=item C<TextTools;Utility>

A text tool utility. (A category, really.)

=item C<DesktopSettings;Settings>

Configuration tool for the GUI.  Example applications are:
F<lxsession-edit.desktop>,
F<qt4config.desktop>,
F<lxsession-default-apps.desktop>,
F<exo-preferred-applications.desktop>,
F<ControlPanel.desktop>,
F<thunar-volman-settings.desktop>,
F<mate-notification-properties.desktop>,
F<mate-window-properties.desktop>,
F<lxappearance.desktop>,
F<gtk-theme-switch2.desktop>,
F<obconf.desktop>,
F<tint2conf.desktop>,
F<mate-appearance-properties.desktop>,
F<libsmfm-pref-apps.desktop>,
F<thunar-settings.desktop>,
F<elementary_config.desktop>,
F<gtk-chtheme.desktop>,
F<pcmanfm-desktop-pref.desktop>,
F<stuurman-desktop-pref.desktop>,
F<libfm-pref-apps.desktop> and
F<gtk2_prefs.desktop>.

=item C<HardwareSettings;Settings>

A tool to manage hardware components, like sound cards, video cards or
printers.  This is really a category and cannot have a preferred
application by category.  Example applications are:
F<cups.desktop>,
F<ffadomixer.desktop>,
F<grandr.desktop>,
F<lxkb-config.desktop>,
F<lxrandr.desktop>,
F<mate-display-properties.desktop>,
F<mate-keyboard.desktop>,
F<mate-settings-mouse.desktop>,
F<redhat-system-config-printer.desktop>,
F<system-config-printer.desktop> and
F<xde-input.desktop>.  There are no commonly known mime types.

=item C<Printing;HardwareSettings;Settings>

A tool to manage printers.
Applications are F<cups.desktop>,
F<redhat-system-config-printer.desktop> and
F<system-config-printer.desktop>.  There are no commonly known mime
types, so preferred applications are tracked by category only.

=item C<PackageManager;Settings>

A package manager application.
F<xfp.desktop> with mime types
F<application/x-deb>,
F<application/x-debian-package>,
F<application/x-rpm>.

=item C<Dialup;Network>

A dial-up program.
F<mandriva-tightvnc.desktop> with no mime types.

=item C<InstantMessaging;Network>

An instant messaging client.
F<empathy.desktop> with no mime types;
F<pidgin.desktop> with no mime types.  These applications are only
tracked by category.

=item C<Chat;Network>

A chat client.
No commonly known applications or mime types.

=item C<IRCClient;Network>

An IRC (Internet Relay Chat) client.
F<hexchat.desktop> with mime types
F<x-scheme-handler/irc> and
F<x-scheme-handler/ircs>.

=item C<Feed;Network>

RSS, podcast and other subscription based contents.
No commonly known applications or mime types.

=item C<FileTransfer;Network>

Tools like FTP or P2P programs.
F<filezilla.desktop> and F<gftp.desktop> but no commonly known mime
types. (But I don't have a  bittorrent client installed.)

=item C<HamRadio;Network>

Tools like FTP or P2P programs.
No commonly known applications or mime types.

=item C<News;Network>

A news reader or a news ticker.
No commonly known applications or mime types.

=item C<P2P;Network>

A P2P program.
No commonly known applications or mime types.

=item C<RemoteAccess;Network>

A tool to remotely manage your PC.
F<remmina.desktop>,
F<telnet.desktop>,
F<mandriva-tightvnc.desktop>,
F<innovidata-opennx-wizard.desktop>,
F<bssh.desktop>,
F<x11vnc.desktop>,
F<ssvnc.desktop>,
F<putty.desktop>,
F<vncviewer.desktop>,
F<innovidata-opennx-admin.desktop>,
F<bvnc.desktop>,
F<innovidata-opennx.desktop>,
F<gdmflexiserver-xnest.desktop> with no mime types.

=item C<Telephony;Network>

Telephony via PC.
F<ekiga.desktop> with no mime types.

=item C<TelephonyTools;Utility>

Telephony tools, to dial a number, manage PBX, etc.
No commonly known applications or mime types.

=item C<VideoConference;Network>

Video conference software.
No commonly known applications or mime types.

=item C<WebBrowser;Network>

A web browser.
F<chromium.desktop> with mime types,
F<text/html>,
F<text/xml>,
F<application/xhtml+xml>,
F<text/mml>,
F<x-scheme-handler/http>,
F<x-scheme-handler/https>,
F<dillo.desktop> with no mime types,
F<elinks.desktop> with mime types,
F<text/html>,
F<eric6_webbrowser.desktop> with mime types,
F<text/html>,
F<text/xml>,
F<application/xhtml+xml>,
F<x-scheme-handler/http>,
F<x-scheme-handler/https>,
F<firefox.desktop> with mime types,
F<text/html>,
F<text/xml>,
F<application/xhtml+xml>,
F<application/xml>,
F<application/rss+xml>,
F<application/rdf+xml>,
F<application/vnd.mozilla.xul+xml>,
F<text/mml>,
F<x-scheme-handler/http>,
F<x-scheme-handler/https>,
F<x-scheme-handler/ftp>,
F<javaws.desktop> with mime types,
F<application/x-java-jnlp-file>,
F<links.desktop> with no mime types,
F<lynx.desktop> with no mime types,
F<midori.desktop> with mime types,
F<text/html>,
F<application/xhtml+xml>,
F<x-scheme-handler/http>,
F<x-scheme-handler/https>,
F<x-scheme-handler/geo>,
F<image/svg+xml>,
F<midori-private.desktop> with mime types,
F<MozillaFirefox.desktop> with mime types,
F<text/html>,
F<text/xml>,
F<application/xhtml+xml>,
F<application/vnd.mozilla.xul+xml>,
F<text/mml>,
F<application/x-xpinstall>,
F<mozilla-firefox.desktop> with mime types,
F<text/html>,
F<text/xml>,
F<application/xhtml+xml>,
F<application/xml>,
F<application/rss+xml>,
F<application/rdf+xml>,
F<application/vnd.mozilla.xul+xml>,
F<text/mml>,
F<x-scheme-handler/http>,
F<x-scheme-handler/https>.

=item C<WebDevelopment;Network>

=item C<WebDevelopment;Development>

A tool for web developers.
No commonly known applications or mime types.

=item C<Midi;Audio;AudioVideo>

An app related to MIDI.
No commonly known applications or mime types.

=item C<Mixer;Audio;AudioVideo>

Just a mixer.
F<alsamixer.desktop>,
F<alsavolume.desktop>,
F<aumix.desktop>,
F<ffadomixer.desktop>,
F<pavucontrol.desktop>,
F<pnmixer.desktop>, with no mime types.

=item C<Sequencer;Audio;AudioVideo>

A sequencer.
No commonly known applications or mime types.

=item C<Tuner;Audio;AudioVideo>

A tuner.
No commonly known applications or mime types.

=item C<TV;Audio;AudioVideo>

A TV application.
Too many to list.  Every video player.

=item C<AudioVideoEditing;Audio>

=item C<AudioVideoEditing;Video>

=item C<AudioVideoEditing;AudioVideo>

Application to edit audio/video files.
These entries are not putting themselves in the right categories.
F<audacity.desktop> with mime types,
F<application/ogg>,
F<audio/basic>,
F<audio/mpeg>,
F<audio/x-aiff>,
F<audio/x-mp3>,
F<audio/x-wav>,
F<application/x-audacity-project>,
F<kdenlive.desktop> with mime types,
F<application/x-kdenlive>,
F<openshot.desktop> with mime types,
F<application/vnd.openshot-project>,
F<org.kde.kdenlive.desktop> with mime types,
F<application/x-kdenlive>,
F<stopmotion.desktop> with mime types,
F<application/x-stopmotion>.

=item C<Player;Audio>

=item C<Player;Video>

=item C<Player;AudioVideo>

Application to play audio/video files.
Too many to list.  Every audio and video player.

=item C<Recorder;Audio>

=item C<Recorder;Video>

=item C<Recorder;AudioVideo>

Application to record audio/video files.
F<org.gnome.Cheese.desktop> with no mime types.

=item C<DiscBurning;AudioVideo>

Application to burn a disc.
F<brasero.desktop> with mime types,
F<application/x-cd-image>,
F<application/x-cdrdao-toc>,
F<application/x-cue>,
F<application/x-toc>,
F<audio/x-scpls>,
F<audio/x-ms-asx>,
F<audio/x-mp3-playlist>,
F<audio/x-mpegurl>,
F<application/x-brasero>,
F<x-content/audio-cdda>,
F<x-content/video-dvd>,
F<x-content/video-vcd>,
F<x-content/video-svcd>,
F<x-content/image-picturecd>,
F<simpleburn.desktop> with no mime types,
F<xfburn.desktop> with mime types,
F<application/x-cd-image>.

=item C<Archiving;Utility>

A tool to archive/backup data.
F<deja-dup.desktop> with no mime types,
F<deja-dup-monitor.desktop> with no mime types,
F<deja-dup-preferences.desktop> with no mime types,
F<file-roller.desktop> with mime types,
F<application/x-7z-compressed>,
F<application/x-7z-compressed-tar>,
F<application/x-ace>,
F<application/x-alz>,
F<application/x-ar>,
F<application/x-arj>,
F<application/x-bzip>,
F<application/x-bzip-compressed-tar>,
F<application/x-bzip1>,
F<application/x-bzip1-compressed-tar>,
F<application/x-cabinet>,
F<application/x-cbr>,
F<application/x-cbz>,
F<application/x-cd-image>,
F<application/x-compress>,
F<application/x-compressed-tar>,
F<application/x-cpio>,
F<application/x-deb>,
F<application/x-ear>,
F<application/x-ms-dos-executable>,
F<application/x-gtar>,
F<application/x-gzip>,
F<application/x-gzpostscript>,
F<application/x-java-archive>,
F<application/x-lha>,
F<application/x-lhz>,
F<application/x-lzip>,
F<application/x-lzip-compressed-tar>,
F<application/x-lzma>,
F<application/x-lzma-compressed-tar>,
F<application/x-lzop>,
F<application/x-lzop-compressed-tar>,
F<application/x-rar>,
F<application/x-rar-compressed>,
F<application/x-rpm>,
F<application/x-rzip>,
F<application/x-tar>,
F<application/x-tarz>,
F<application/x-stuffit>,
F<application/x-war>,
F<application/x-xz>,
F<application/x-xz-compressed-tar>,
F<application/x-zip>,
F<application/x-zip-compressed>,
F<application/x-zoo>,
F<application/zip>,
F<flburn.desktop> with no mime types,
F<gnome-file-roller.desktop> with mime types,
F<application/x-7z-compressed>,
F<application/x-7z-compressed-tar>,
F<application/x-ace>,
F<application/x-alz>,
F<application/x-ar>,
F<application/x-arj>,
F<application/x-bzip>,
F<application/x-bzip-compressed-tar>,
F<application/x-bzip1>,
F<application/x-bzip1-compressed-tar>,
F<application/x-cabinet>,
F<application/x-cbr>,
F<application/x-cbz>,
F<application/x-cd-image>,
F<application/x-compress>,
F<application/x-compressed-tar>,
F<application/x-cpio>,
F<application/x-deb>,
F<application/x-ear>,
F<application/x-ms-dos-executable>,
F<application/x-gtar>,
F<application/x-gzip>,
F<application/x-gzpostscript>,
F<application/x-java-archive>,
F<application/x-lha>,
F<application/x-lhz>,
F<application/x-lrzip>,
F<application/x-lrzip-compressed-tar>,
F<application/x-lzip>,
F<application/x-lzip-compressed-tar>,
F<application/x-lzma>,
F<application/x-lzma-compressed-tar>,
F<application/x-lzop>,
F<application/x-lzop-compressed-tar>,
F<application/x-ms-wim>,
F<application/x-rar>,
F<application/x-rar-compressed>,
F<application/x-rpm>,
F<application/x-rzip>,
F<application/x-tar>,
F<application/x-tarz>,
F<application/x-stuffit>,
F<application/x-war>,
F<application/x-xz>,
F<application/x-xz-compressed-tar>,
F<application/x-zip>,
F<application/x-zip-compressed>,
F<application/x-zoo>,
F<application/zip>,
F<roller.desktop> with no mime types,
F<xarchiver.desktop> with mime types,
F<application/x-arj>,
F<application/arj>,
F<application/x-bzip>,
F<application/x-bzip-compressed-tar>,
F<application/x-gzip>,
F<application/x-rar>,
F<application/x-rar-compressed>,
F<application/x-tar>,
F<application/x-zip>,
F<application/x-zip-compressed>,
F<application/zip>,
F<application/x-7z-compressed>,
F<application/x-compressed-tar>,
F<application/x-bzip2>,
F<application/x-bzip2-compressed-tar>,
F<application/x-lzma>,
F<application/x-lzma-compressed-tar>,
F<application/x-lzop>,
F<application/x-lzop-compressed-tar>,
F<application/x-xz>,
F<application/x-xz-compressed-tar>,
F<application/x-deb>,
F<application/x-rpm>,
F<xfburn.desktop> with mime types,
F<application/x-cd-image>.

=item C<Compression;Archiving;Utility>

A tool to manage compressed data/archives.
F<file-roller.desktop> with mime types as above,
F<gnome-file-roller.desktop> with mime types as above.

=item C<FileManager;FileTools;System>

A file manager.
F<caja.desktop> with no mime types,
F<emelfm2.desktop> with mime types,
F<inode/directory>,
F<inode/mount-point>,
F<enlightenment_filemanager.desktop> with mime types,
F<inode/directory>,
F<fluff.desktop> with no mime types,
F<mandriva-rox.desktop> with no mime types,
F<mc.desktop> with no mime types,
F<PathFinder.desktop> with no mime types,
F<pcmanfm.desktop> with mime types,
F<inode/directory>,
F<rox.desktop> with no mime types,
F<rox-filer.desktop> with no mime types,
F<spacefm.desktop> with mime types,
F<inode/directory>,
F<inode/mount-point>,
F<x-scheme-handler/ssh>,
F<x-scheme-handler/smb>,
F<x-scheme-handler/nfs>,
F<x-scheme-handler/ftp>,
F<stuurman.desktop> with mime types,
F<x-directory/normal>,
F<inode/directory>,
F<Thunar.desktop> with no mime types,
F<Thunar-folder-handler.desktop> with mime types,
F<x-directory/gnome-default-handler>,
F<x-directory/normal>,
F<inode/directory>,
F<vifm.desktop> with mime types,
F<inode/directory>,
F<xfe.desktop> with mime types,
F<text/plain>.

=item C<TerminalEmulator;System>

A terminal emulator application.
F<aterm.desktop>,
F<eterm.desktop>,
F<fedora-xterm.desktop>,
F<gksu.desktop>,
F<lxterminal.desktop>,
F<mageia-xterm.desktop>,
F<mandriva-xterm.desktop>,
F<pterm.desktop>,
F<roxterm.desktop>,
F<rpmforge-rxvt-unicode.desktop>,
F<terminal-as-root-(gksu).desktop>,
F<terminals.desktop>,
F<urxvtc.desktop>,
F<urxvt.desktop>,
F<urxvt-tabbed.desktop>,
F<uxterm.desktop>,
F<xterm.desktop>,
F<xterm-(unicode).desktop>: all with no mime types.

=item C<Filesystem;System>

A file system tool.
Applications are:
F<gparted.desktop> and
F<Thunar-bulk-rename.desktop>, with no mime types.

=item C<Monitor;System>

=item C<Monitor;Network>

Monitor application/applet that monitors some resource or activity.
Applications are:
F<boinc.desktop>,
F<boinc-manager.desktop>,
F<bonobo-browser.desktop>,
F<etherape.desktop>,
F<ettercap.desktop>,
F<gsmartcontrol.desktop>,
F<lxtask.desktop>,
F<manage-print-jobs.desktop>,
F<mandriva-xkill.desktop>,
F<print-applet.desktop>,
F<redhat-manage-print-jobs.desktop>,
F<redhat-print-applet.desktop>,
F<wireshark-gtk.desktop> with mime types
F<application/vnd.tcpdump.pcap>,
F<application/x-pcapng>,
F<application/x-snoop>,
F<application/x-iptrace>,
F<application/x-lanalyzer>,
F<application/x-nettl>,
F<application/x-radcom>,
F<application/x-etherpeek>,
F<application/x-visualnetworks>,
F<application/x-netinstobserver>,
F<application/x-5view> and
F<application/x-tektronix-rf5>;
F<xdg-assist.desktop>,
F<xdg-monitor.desktop>,
F<xload.desktop>,
F<xsensors.desktop>,
F<zenmap.desktop> and
F<zenmap-root.desktop>.
This is really more of a category as the monitors are for various
purposes.

=item C<Security;System>

=item C<Security;Settings>

A security tool. Applications are:
F<ettercap.desktop> with no mime types; and
F<fwbuilder.desktop> with mime type
F<text/x-xml-fwbuilder>.  This is more of a category than a preferred
application type.

=item C<Accessibility;Settings>

=item C<Accessibility;Utility>

Accessibility.  Applications are F<dasher.desktop> with no mime types.

=item C<Calculator;Utility>

A calculator.  Applications are:
F<calcoo.desktop>,
F<gcalctool.desktop>,
F<calculator.desktop>,
F<gnome-gcalctool.desktop> and
F<xcalc.desktop>: all with no known mime types.  These applications are
tracked only by category.

=item C<Clock;Utility>

A clock application/applet.  Applications are:
F<wmitime.desktop>.  Strangely there are many more clock applications,
but they do not have the appropriate categories set.  There are no
known mime types.  These applications are only tracked by category.

=item C<TextEditor;Utility>

A text editor.

F<adie.desktop> with mime types
F<application/x-shellscript>,
F<text/english>,
F<text/plain>,
F<text/x-c>,
F<text/x-c++>,
F<text/x-c++hdr>,
F<text/x-chdr>,
F<text/x-c++src>,
F<text/x-csrc>,
F<text/x-java>,
F<text/x-makefile>,
F<text/x-moc>,
F<text/x-pascal>,
F<text/x-tcl> and
F<text/x-tex>;
F<bvi.desktop> with mime types
F<application/octet-stream>;
F<bviplus.desktop> with mime types
F<application/octet-stream>;
F<fltk-editor.desktop>,
F<gedit.desktop> with mime types
F<application/x-shellscript>,
F<text/plain>,
F<text/x-c>,
F<text/x-c++>,
F<text/x-c++hdr>,
F<text/x-chdr>,
F<text/x-c++src>,
F<text/x-csrc>,
F<text/x-java>,
F<text/x-makefile>,
F<text/x-moc>,
F<text/x-pascal>,
F<text/x-tcl> and
F<text/x-tex>;
F<gvim.desktop> with mime types
F<application/x-shellscript>,
F<text/english>,
F<text/plain>,
F<text/x-c>,
F<text/x-c++>,
F<text/x-chdr>,
F<text/x-c++hdr>,
F<text/x-csrc>,
F<text/x-c++src>,
F<text/x-java>,
F<text/x-makefile>,
F<text/x-moc>,
F<text/x-pascal>,
F<text/x-tcl> and
F<text/x-tex>;
F<mcedit.desktop>,
F<nano.desktop>,
F<vi.desktop> with mime types
F<application/x-shellscript>,
F<text/english>,
F<text/plain>,
F<text/x-c>,
F<text/x-c++>,
F<text/x-chdr>,
F<text/x-c++hdr>,
F<text/x-csrc>,
F<text/x-c++src>,
F<text/x-java>,
F<text/x-makefile>,
F<text/x-moc>,
F<text/x-pascal>,
F<text/x-tcl> and
F<text/x-tex>;
F<vim.desktop> with mime types
F<application/x-shellscript>,
F<text/english>,
F<text/plain>,
F<text/x-c>,
F<text/x-c++>,
F<text/x-chdr>,
F<text/x-c++hdr>,
F<text/x-csrc>,
F<text/x-c++src>,
F<text/x-java>,
F<text/x-makefile>,
F<text/x-moc>,
F<text/x-pascal>,
F<text/x-tcl> and
F<text/x-tex>;
F<xedit.desktop> and
F<xfw.desktop> with mime type
F<text/plain>.

=item C<Documentation>

Help or documentation. Applications are:
F<assistant.desktop> with mime type
F<application/x-assistant>;
F<mate-user-guide.desktop>,
F<TUV.desktop> and
F<yelp.desktop> with mime types
F<application/docbook+xml>,
F<x-scheme-handler/ghelp>,
F<x-scheme-handler/help>,
F<x-scheme-handler/info> and
F<x-scheme-handler/man>.  These applications are better tracked by mime
type than by category (which is quite general).

=item C<Screensaver>

A screen saver (launching this desktop entry should activate the screen
saver).  Strangely, this category is not associated with the many screen
savers loaded on my Arch Linux system.  These must be tracked by
category; however, correction of F<.desktop> files to include this
category is necessary.

=item C<TrayIcon>

An application that is primarily an icon for the "system tray" or
"notification area" (apps that open a normal window and just happen to
have a tray icon as well should not list this category).

Example applications are:
F<alltray.desktop>,
F<cbatticon.desktop>,
F<dhcpcd-gtk.desktop>,
F<fbxkb.desktop>,
F<ftmenu.desktop>,
F<gatotray.desktop>,
F<moc-tray.desktop>,
F<peksystray.desktop>,
F<pnmixer.desktop>,
F<sbxkb.desktop>,
F<sd-applet.desktop>,
F<stalonetray.desktop>,
F<wmsystemtray.desktop>,
F<xdg-monitor.desktop> and
F<xdg-traymenu.desktop>.
This is really a general category and there are no tracked preferred
applications in this category.

=item C<Applet>

An applet that will run inside a panel or another such application,
likely desktop specific.

=item C<DockApp>

A WindowMaker style dock application.  Example applications:
F<allin1.desktop>,
F<AlsaMixer.app.desktop>,
F<asclock.desktop>,
F<asclock-gtk.desktop>,
F<asclock-xlib.desktop>,
F<bubblemon.desktop>,
F<flipse.desktop>,
F<lal.desktop>,
F<peksystray.desktop>,
F<volume-app.desktop>,
F<wmacpi.desktop>,
F<wmappl.desktop>,
F<wmauda.desktop>,
F<wmbatteries.desktop>,
F<wmbattery.desktop>,
F<wmbiff.desktop>,
F<wmBinClock.desktop>,
F<wmblob.desktop>,
F<wmblueclock.desktop>,
F<wmbluecpu.desktop>,
F<wmbluegpu.desktop>,
F<wmbluemem.desktop>,
F<wmbubble.desktop>,
F<wmbutton.desktop>,
F<wmcalc.desktop>,
F<wmCalClock.desktop>,
F<wmCalClockKbd.desktop>,
F<wmcdplay.desktop>,
F<wmcliphist.desktop>,
F<wmclock.desktop>,
F<wmclockmon.desktop>,
F<wmcore.desktop>,
F<wmcpu.desktop>,
F<wmcpuload.desktop>,
F<wmcpumon.desktop>,
F<wmdiskmon.desktop>,
F<wmfire.desktop>,
F<wmforkplop.desktop>,
F<wmfrog.desktop>,
F<wmgtemp.desktop>,
F<wmifinfo.desktop>,
F<wmifs.desktop>,
F<wminet.desktop>,
F<wmitime.desktop>,
F<wmmail.desktop>,
F<wmmaiload.desktop>,
F<wmMand.desktop>,
F<wmmixer.desktop>,
F<wmMoonClock.desktop>,
F<wmnd.desktop>,
F<wmnet.desktop>,
F<wmsmixer.desktop>,
F<wmstickynotes.desktop>,
F<wmsysmon.desktop>,
F<wmsystemtray.desktop>,
F<wmsystray.desktop>,
F<wmtime.desktop>,
F<wmtimer.desktop>,
F<wmtop.desktop>,
F<wmtrash.desktop>,
F<wmudmount.desktop>,
F<wmwave.desktop>,
F<wmWeather.desktop>,
F<wmweather+.desktop>,
F<wmwifi.desktop> and
F<wmwork.desktop>.

This is really a general category and preferred applications are not
tracked in this category.

=item C<Shell>

A shell (an actual specific shell such as bash or tcsh, not a
TerminalEmulator).

Applications are:
F<tkwish8.6.desktop>.

The preferred shell should be set by other means.

=back

=head1 FILE FORMAT

There are two formats of file:

=over

=item 1.

Mime application file format that is compliant to the XDG mime
application specification.

=item 2.

XDG category file format that is similar to the XDG mime application
specification but uses XDG categories instead of mime types.

=back

=head2 MIME APPLICATIONS

For applications that are set by default the XDG mime applications
specification is used to store the default applications, added
associations and removed associations.  Files are searched in the
following order:

=over

=item F<$XDG_CONFIG_HOME/$XDG_CURRENT_DESKTOP-mimeapps.list>

This file is desktop environment specific.
Only considered for defaults and not associations.

=item F<$XDG_CONFIG_HOME/mimeapps.list>

Considered for both defaults and associations.

=item F<$XDG_CONFIG_DIRS/$XDG_CURRENT_DESKTOP-mimeapps.list>

This file is desktop environment specific.
Only considered for defaults and not associations.

=item F<$XDG_CONFIG_DIRS/mimeapps.list>

Considered for both defaults and associations.

=item F<$XDG_DATA_HOME/applications/$XDG_CURRENT_DESKTOP-mimeapps.list>

This file is desktop environment specific.
Only considered for defaults and not associations.
This location is deprecated but available for backward compatibility.

=item F<$XDG_DATA_HOME/applications/mimeapps.list>

Considered for both defaults and associations.
This location is deprecated but available for backward compatibility.

=item F<$XDG_DATA_DIRS/applications/$XDG_CURRENT_DESKTOP-mimeapps.list>

This file is desktop environment specific.
Only considered for defaults and not associations.
This location is deprecated but available for backward compatibility.

=item F<$XDG_DATA_DIRS/applications/mimeapps.list>

Considered for both defaults and associations.
This location is deprecated but available for backward compatibility.

=back

=head3 EXAMPLE

Following is an example of the contents of a F<mimeapps.list> file:

 [Added Associations]
 application/pdf=zat.desktop;zathura.desktop;raktpdf.desktop;gvim.desktop;
 application/x-ole-storage=libreoffice-startcenter.desktop;
 application/x-desktop=gvim.desktop;
 image/jpeg=xv.desktop;flphoto.desktop;gpicview.desktop;
 image/png=gpicview.desktop;
 application/octet-stream=bvi.desktop;wireshark.desktop;
 text/html=firefox.desktop;
 text/plain=vim.desktop;
 
 [Default Applications]
 x-scheme-handler/mailto=kde4-kmailservice.desktop
 application/x-extension-eml=kde4-kmailservice.desktop
 message/rfc822=kde4-kmailservice.desktop
 application/octet-stream=bvi.desktop
 text/plain=vim.desktop

=head2 XDG CATEGORIES

For preferences that are set by category, B<xdg-prefs> maintains a
separate F<prefapps.list> file that is similar in format to the
F<mimeapps.list> file of the XDG mime applications specification with
the exception that the XDG category is used in place of the mime type as
a key in the various sections of the file.  As for the F<mimeapps.list>
files, F<prefapps.list> files are searched in the following order:

=over

=item F<$XDG_CONFIG_HOME/$XDG_CURRENT_DESKTOP-prefapps.list>

This file is desktop environment specific.
Only considered for defaults and not associations.

=item F<$XDG_CONFIG_HOME/prefapps.list>

Considered for both defaults and associations.

=item F<$XDG_CONFIG_DIRS/$XDG_CURRENT_DESKTOP-prefapps.list>

This file is desktop environment specific.
Only considered for defaults and not associations.

=item F<$XDG_CONFIG_DIRS/prefapps.list>

Considered for both defaults and associations.

=item F<$XDG_DATA_HOME/applications/$XDG_CURRENT_DESKTOP-prefapps.list>

This file is desktop environment specific.
Only considered for defaults and not associations.
This location is deprecated but available for backward compatibility.

=item F<$XDG_DATA_HOME/applications/prefapps.list>

Considered for both defaults and associations.
This location is deprecated but available for backward compatibility.

=item F<$XDG_DATA_DIRS/applications/$XDG_CURRENT_DESKTOP-prefapps.list>

This file is desktop environment specific.
Only considered for defaults and not associations.
This location is deprecated but available for backward compatibility.

=item F<$XDG_DATA_DIRS/applications/prefapps.list>

Considered for both defaults and associations.
This location is deprecated but available for backward compatibility.

=back

=head3 EXAMPLE

Following is an example of the contents of a F<prefapps.list> file:

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
