=pod

=head1 NAME

xdg-prefs - locate and set preferred desktop applications

=head1 SYNOPSIS

B<xdg-prefs> [I<options>] {-l,--list} [--] I<TYPE> [...]

B<xdg-prefs> [I<options>] {-p,--pref} [--] I<APPID>[:I<ACTION>][B<;>...] [I<TYPE> [...]]

=head1 DESCRIPTION

B<xdg-prefs> operates in two modes: (1) locates preferred applications
by category or mime type; and (2) sets preferred applications by
category or mime type.

=head1 ARGUMENTS

The program accepts the following arguments:

=over

=item I<APPID>[:I<ACTION>][B<;>...]

Specifies the application identifier of an XDG desktop application to
locate.  The application identifier, I<APPID>, can be one of the
following:

=over

=item 1.

the name of a desktop entry file without the F<.desktop> suffix (e.g.
C<gvim>); the name may contain a C</> if it is specified relative to a
user or system application directory, in which case it must not start
with a C</> or C<.>.

=item 2.

the name of a desktop entry file with the F<.desktop> suffix (e.g.
C<gvim.desktop>); the same restrictions as (1), above, apply; or,

=item 3.

the full path (absolute or relative) and filename of a desktop entry
file (e.g.  F</usr/share/applications/gvim.desktop>); the full path must
contain at least one C</> and start with either a C</> or a C<.>.

=back

The optional action, I<ACTION>, can be specified after a colon so that
actions within desktop entries can be identified.

Additional application identifiers and option actions can be listed
separated by semi-colons (C<;>).

Providing a non-option application identifier argument is mandatory when
the B<--pref> option is specified.

=item I<TYPE>

Specifies the type of application for which to show or set I<APPID>
as the preferred application.  The application type, I<TYPE>, can be one
of the following:

=over

=item 1.

A recognized XDG category name.  For recognized XDG category names, see
L</XDG CATEGORIES>.

=item 2.

A mime (content) type.  All mime types have a C</> in their names and
are thus distinguished from XDG categories.  The content type cannot
contain wild cards (i.e. it cannot contain C<*>).

=back

=back

=head1 OPTIONS

The options that are detailed below are recognized by B<xdg-prefs>.
B<xdg-which> uses L<getopt_long_only(3)>, so unambiguous abbreviations
of long options and long options with a single dash are also supported.

=head2 COMMAND OPTIONS

One of the following command options must be specified to set the
command mode:

=over

=item B<-l>, B<--list> [--] I<TYPE> [...]

=item B<-p>, B<--pref> [--] I<APPID> [I<TYPE> [...]]

=item B<-h>, B<--help>, B<-H>, B<-?>, B<--?>

=item B<-V>, B<--version>

=item B<-C>, B<--copying>

=back

=head2 GENERAL OPTIONS

The following general options are recognized:


=head1 XDG CATEGORIES

The following XDG categories are recognized and tracked by the program:

=over

=item C<Calendar>

Calendar, task manager and scheduling programs.

=item C<ContactManager>

Address books, contact lists, LDIF file manipulation.

=item C<Dictionary>

=item C<Email>

=item C<Presentation>

=item C<Spreadsheet>

=item C<WordProcessor>

=item C<2DGraphics>

=item C<Viewer>

=item C<Printing>

=item C<PackageManager>

=item C<IIRCClient>

=item C<Feed>

=item C<FileTransfer>

=item C<News>

=item C<RemoteAccess>

=item C<Telephony>

=item C<VideoConference>

=item C<WebBrowser>

=item C<Mixer>

=item C<Player>

=item C<Recorder>

=item C<DiscBurning>

=item C<Archiving>

=item C<FileManager>

=item C<TerminalEmulator>

=item C<Monitor>

=item C<Calculator>

=item C<Clock>

=item C<TextEditor>

=item C<Documentation>

=back

=head1 FILE FORMAT

=head2 MIME APPLICATIONS

For applications that are set by default the XDG mime applications
specification is used to store the default applications, added
associations and removed associations.  Files are searched in the
following order:

=over

=item F<$XDG_CONFIG_HOME/$XDG_CURRENT_DESKTOP-mimeapps.list>

=item F<$XDG_CONFIG_HOME/mimeapps.list>

=item F<$XDG_CONFIG_DIRS/$XDG_CURRENT_DESKTOP-mimeapps.list>

=item F<$XDG_CONFIG_DIRS/mimeapps.list>

=item F<$XDG_DATA_HOME/applications/$XDG_CURRENT_DESKTOP-mimeapps.list>

=item F<$XDG_DATA_HOME/applications/mimeapps.list>

=item F<$XDG_DATA_DIRS/applications/$XDG_CURRENT_DESKTOP-mimeapps.list>

=item F<$XDG_DATA_DIRS/applications/mimeapps.list>

=back

=head2 XDG CATEGORIES

For preferences that are set by category, B<xdg-prefs> maintains a
separate F<prefapps.list> file that is similar in format to the
F<mimeapps.list> file of the XDG mime applications specification with
the exception that the XDG category is used in place of the mime type as
a key in the various sections of the file.  As for the F<mimeapps.list>
files, F<prefapps.list> files are searched in the following order:

=over

=item F<$XDG_CONFIG_HOME/$XDG_CURRENT_DESKTOP-prefapps.list>

=item F<$XDG_CONFIG_HOME/prefapps.list>

=item F<$XDG_CONFIG_DIRS/$XDG_CURRENT_DESKTOP-prefapps.list>

=item F<$XDG_CONFIG_DIRS/prefapps.list>

=item F<$XDG_DATA_HOME/applications/$XDG_CURRENT_DESKTOP-prefapps.list>

=item F<$XDG_DATA_HOME/applications/prefapps.list>

=item F<$XDG_DATA_DIRS/applications/$XDG_CURRENT_DESKTOP-prefapps.list>

=item F<$XDG_DATA_DIRS/applications/prefapps.list>

=back

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
