=pod

=head1 NAME

xdg-xsession - an XDG compliant XSession startup notification launcher

=head1 SYNOPSIS

B<xdg-xsession> [I<OPTIONS>] [I<APPID> [I<FILE>|I<URL>]]

B<xdg-xsession> [I<OPTIONS>] -c I<command and arguments>

=head1 DESCRIPTION

B<xdg-xsession> is a script that simply executes L<xdg-launch(1)> with
the appropriate arguments (B<--xsession>).

=head1 SEE ALSO

L<xdg-launch(1)>.

=head1 AUTHOR

Brian Bidulock E<lt>bidulock@openss7.orgE<gt>

=cut

# vim: sw=4 tw=72 nocin
