=pod

=head1 NAME

xdg-autostart - an XDG compliant autostart startup notification launcher

=head1 SYNOPSIS

B<xdg-autostart> [I<OPTIONS>] [I<APPID> [I<FILE>|I<URL>]]

B<xdg-autostart> [I<OPTIONS>] -c I<command and arguments>

=head1 DESCRIPTION

B<xdg-autostart> is a script that simply executes L<xdg-launch(1)> with
the appropriate arguments (B<--autostart>).
See L<xdg-launch(1)/COMMAND OPTIONS> for more information.

=head1 BUGS

B<xdg-autostart> has no known bugs.
Please report bugs to the source code repository at
L<https://github.com/bbidulock/xdg-launch/issues>.

=head1 SEE ALSO

L<xdg-launch(1)>.

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
