#!/bin/sh
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache="$cachedir/dmenu_launch"
else
	cache="$HOME/.dmenu_cache" # if no xdg dir, fall back to dotfile in ~
fi
XDG_DATA_HOME=${XDG_DATA_HOME:-"$HOME/.local/share"}
XDG_DATA_DIRS=${XDG_DATA_DIRS:-"/usr/local/share:/usr/share"}
DIRS=
for dir in $(echo "$XDG_DATA_HOME:$XDG_DATA_DIRS"|tr ':' ' '); do
	DIRS="$DIRS $dir/applications"
done
if stest -dqr -n "$cache" $DIRS; then
	stest -fl $DIRS | grep '\.desktop$' | sed 's,\.desktop$,,' | sort -u | tee "$cache"
else
	cat "$cache"
fi
